# Build and package only explicit release files; never copy local environments or recordings.
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$version = (Get-Content -LiteralPath (Join-Path $projectRoot 'VERSION') -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') { throw 'VERSION must contain a release version such as 0.1.2.' }
$packageName = "Speaker-Studio-$version-windows-x64"
$dist = Join-Path $projectRoot 'dist'
$stage = Join-Path $dist ($packageName + '-stage-' + [guid]::NewGuid().ToString('N'))
$bundle = Join-Path $stage $packageName
$zipPath = Join-Path $dist ($packageName + '.zip')
$exePath = Join-Path $dist ($packageName + '.exe')
New-Item -ItemType Directory -Path $bundle -Force | Out-Null

Push-Location $projectRoot
try {
    cargo build --release --locked --target x86_64-pc-windows-msvc
    if ($LASTEXITCODE -ne 0) { throw 'Release build failed.' }
    $builtExe = Join-Path $projectRoot 'target\x86_64-pc-windows-msvc\release\speaker-studio.exe'
    if ((Get-Item -LiteralPath $builtExe).VersionInfo.ProductVersion -ne $version) {
        throw 'Executable version does not match VERSION.'
    }
    Copy-Item -LiteralPath $builtExe -Destination (Join-Path $projectRoot 'Speaker Studio.exe') -Force
    Copy-Item -LiteralPath $builtExe -Destination (Join-Path $bundle 'Speaker Studio.exe')
    Copy-Item -LiteralPath $builtExe -Destination $exePath -Force
    $files = @(
        'Start Speaker Studio.bat', 'start.ps1', 'VERSION', 'LICENSE', 'CHANGELOG.md',
        'engine\engine.py', 'engine\requirements.txt',
        'docs\USER_GUIDE.md', 'docs\WINDOWS_DOWNLOAD.md'
    )
    foreach ($file in $files) {
        $destination = Join-Path $bundle $file
        New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force | Out-Null
        Copy-Item -LiteralPath (Join-Path $projectRoot $file) -Destination $destination
    }
    @"
Speaker Studio $version for Windows x64

Read docs\WINDOWS_DOWNLOAD.md for setup requirements, then run Start Speaker Studio.bat.
This package includes the compiled app. Rust and C++ build tools are not required.
Python 3.11, Git, FFmpeg, and the Microsoft Visual C++ runtime are prerequisites.
The first run downloads the speech dependencies and models; an internet connection is required.
Source and updates: https://github.com/krakenunbound/speaker-studio
"@ | Set-Content -LiteralPath (Join-Path $bundle 'START-HERE.txt') -Encoding UTF8
    Compress-Archive -LiteralPath $bundle -DestinationPath $zipPath -Force
    $checksums = foreach ($file in @($zipPath, $exePath)) {
        '{0}  {1}' -f (Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant(), (Split-Path -Leaf $file)
    }
    $checksums | Set-Content -LiteralPath (Join-Path $dist 'SHA256SUMS.txt') -Encoding Ascii
    Write-Output "Release files: $zipPath, $exePath, SHA256SUMS.txt"
} finally {
    Pop-Location
    # The stage is generated by this script, and must remain strictly inside dist.
    $resolvedDist = (Resolve-Path -LiteralPath $dist).Path.TrimEnd('\')
    $resolvedStage = (Resolve-Path -LiteralPath $stage).Path
    if (-not $resolvedStage.StartsWith($resolvedDist + '\', [StringComparison]::OrdinalIgnoreCase)) {
        throw 'Refusing to remove a staging directory outside dist.'
    }
    Remove-Item -LiteralPath $resolvedStage -Recurse -Force
}
